### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by azad327** [IshiniKiridena/Delivery-and-Management-System-KiaOra#1]
In this repo the database script not available please share

**Comment by IshiniKiridena** [comment]
Hi, by scripts I guess you are referring to DB queries . The relevant DB queries are in each of the Utill files
Eg: Bill related queries 
	src/com/finance/BillDBUtill.java
	Insert query is in line 27 inside insertBill() method

As the MVC structure has been used here all the DB queries are managed as such. Each util file contains methods that will support different DB queries as per their implementation. 

PS - Models are managed in a different file.

**Comment by azad327** [comment]
Dear sir, I want of backup of Database. In form of .SQL, .MDF or in .bak.

**Comment by IshiniKiridena** [comment]
I'm sorry, but we're unable to share that data. This application was custom-built for a specific company's use.
